# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transactions.proto
"""Generated protocol buffer code."""
from proto_files.market_pb2 import *
from proto_files import market_pb2 as market__pb2
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12transactions.proto\x12\x05proto\x1a\x0cmarket.proto\"z\n\x10PaymentsResponse\x12\x10\n\x08\x61pproach\x18\x01 \x01(\x05\x12\"\n\x04json\x18\x02 \x03(\x0b\x32\x14.proto.MatchResponse\x12\x30\n\x0ctransactions\x18\x03 \x03(\x0b\x32\x1a.proto.TransactionResponse\".\n\x0bJsonReceipt\x12\x11\n\tpaymentID\x18\x01 \x01(\t\x12\x0c\n\x04txID\x18\x02 \x01(\t\"4\n\x0cListReceipts\x12$\n\x08receipts\x18\x01 \x03(\x0b\x32\x12.proto.JsonReceipt\"\x16\n\x08IssuerId\x12\n\n\x02id\x18\x01 \x01(\t\"*\n\x13TransactionResponse\x12\x13\n\x0btransaction\x18\x01 \x01(\x0c\x32\x81\x01\n\x13TransactionsService\x12\x31\n\x0c\x41\x64\x64TxReceipt\x12\x13.proto.ListReceipts\x1a\x0c.proto.Empty\x12\x37\n\x0bGetPayments\x12\x0f.proto.IssuerId\x1a\x17.proto.PaymentsResponseP\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transactions_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _PAYMENTSRESPONSE._serialized_start = 43
    _PAYMENTSRESPONSE._serialized_end = 165
    _JSONRECEIPT._serialized_start = 167
    _JSONRECEIPT._serialized_end = 213
    _LISTRECEIPTS._serialized_start = 215
    _LISTRECEIPTS._serialized_end = 267
    _ISSUERID._serialized_start = 269
    _ISSUERID._serialized_end = 291
    _TRANSACTIONRESPONSE._serialized_start = 293
    _TRANSACTIONRESPONSE._serialized_end = 335
    _TRANSACTIONSSERVICE._serialized_start = 338
    _TRANSACTIONSSERVICE._serialized_end = 467
# @@protoc_insertion_point(module_scope)
